### ISSUE TITLE
createPDF function hangs in Linux runners (but works fine in Windows)

### ISSUE THREAD

**Issue by jorge-abarca** [peter-murray/github-security-report#14]
The [`createPDF`](https://github.com/peter-murray/github-security-report-action/blob/main/src/pdf/pdfWriter.ts#L5) function in `pdfWriter` hangs when being executed by Linux runners, this even causes the [`Manual Test`](https://github.com/peter-murray/github-security-report-action/blob/main/.github/workflows/manual_test_repo.yml) and [`Build and Test`](https://github.com/peter-murray/github-security-report-action/blob/main/.github/workflows/build_and_test.yml) workflows to fail (given they are using a Linux image themselves). Interestingly enough, this issue doesn't affect Windows runners.

The root cause seems to be [related to the parameters being passed](https://github.com/puppeteer/puppeteer/issues/7862#issuecomment-1159724770) when calling [`puppeteer.launch`](https://github.com/peter-murray/github-security-report-action/blob/main/src/pdf/pdfWriter.ts#L11), [I have a PR open that fixes this issue](https://github.com/peter-murray/github-security-report-action/pull/9), but here is some code [I borrowed from stackoverflow](https://stackoverflow.com/a/61050539) if you are in the middle of some refactoring and don't feel like going through all the commits:

```javascript
      return puppeteer.launch({
        executablePath: revisionInfo.executablePath,
        headless: true,
        devtools: true,
        args: [
          '--ignore-certificate-errors',
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--disable-accelerated-2d-canvas',
          '--disable-gpu'
              ]
        })
```

I have tested this fix for both Linux and Windows runners. While this is not a critical issue, it is quite a head-scratcher given that it silently fails. In our case we would find some workflows with reports generated and others without any reports.

**Comment by peter-murray** [comment]
I had picked up some of these settings when updating the libraries, but have included a couple more of them from your suggestion. I do not agree with the `--ignore-certificate-errors` as there should be none loading a local file, so have not included that one.
